config/routes.rb
Countryplaces::Application.routes.draw do

  root to: 'pages#home'
  match '/financing', to: 'pages#financing'
  match '/properties', to: 'pages#properties'
  match '/about', to: 'pages#about'
  match '/contact', to: 'pages#contact'
  match '/landblog', to: 'pages#landblog'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def properties
  end

  def financing
  end

  def about
  end

  def contact
  end

  def landblog
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def full_title(page_title)
        base_title = "Country Places Inc"
        if page_title.empty?
            base_title
        else
            "#{base_title} | #{page_title}"
        end
    end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
    <header class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "sample app", root_path, id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Home",    root_path %></li>
              <li><%= link_to "Contact",    contact_path %></li>
              <li><%= link_to "Properties",    properties_path %></li>
              <li><%= link_to "Sign in", '#' %></li>
            </ul>
          </nav>
        </div>
      </div>
    </header>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<% provide(:company, 'Country Places Inc') %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/pages/contact.html.erb
<% provide(:title, 'Contact Us') %>
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/pages/financing.html.erb
<% provide(:title, 'Financing') %>
<h1>StaticPages#financing</h1>
<p>Find me in app/views/static_pages/financing.html.erb</p>

app/views/pages/home.html.erb
<% provide(:title, 'Home') %>
<div class="center hero-unit">
  <h1>Welcome to the Sample App</h1>

  <h2>
    This is the home page for the
    <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

  <%= link_to "Sign up now!", '#', class: "btn btn-large btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>

app/views/pages/landblog.html.erb
<% provide(:title, 'Land Blog') %>
<h1>StaticPages#landblog</h1>
<p>Find me in app/views/static_pages/landblog.html.erb</p>

app/views/pages/properties.html.erb
<% provide(:title, 'Properties') %>
<h1>StaticPages#Properties</h1>
<p>Find me in app/views/static_pages/properties.html.erb</p>